dist: trusty
sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

jobs:
  include:
    - &test
      name: "Lint & Unit tests: PHP 7.0, TYPO3v8"
      php: 7.0
      env: TYPO3_VERSION=^8.7
      install:
        - composer require typo3/cms-core="$TYPO3_VERSION"
      script:
        - composer lint:php

    - <<: *test
      name: "Lint & Unit tests: PHP 7.2, TYPO3v9"
      php: 7.2
      env: TYPO3_VERSION=^9.5

    - <<: *test
      name: "Lint & Unit tests: PHP 7.1, TYPO3v8"
      php: 7.1

    - php: 7.1
      name: TypoScript lint
      script:
        - composer lint:typoscript

    - php: 7.1
      name: XML lint
      script:
        - composer lint:xml

    - php: 7.1
      name: Codestyle
      script:
        - composer lint:style

    - php: 7.2
      name: Static analysis
      install:
        - composer require --dev phpstan/phpstan:^0.10
      script:
        - composer analyze:php
