language: php

php:
  - 7.2

sudo: false

addons:
  apt:
    packages:
      - parallel

before_install:
  - phpenv config-rm xdebug.ini

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
