language: php

php:
  - 7.2

env:
  matrix:
    - TYPO3_VERSION=9.5.*

sudo: false

addons:
  apt:
    packages:
      - parallel

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
