language: php
sudo: required
addons:
  sonarcloud:
    organization: "nitsan-technologies-github"
    branches:
      - master
      - develop
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache

# Do not build feature branches or alpha/beta releases
branches:
  only:
    - master
    - develop

# Inform me about failures
notifications:
  email:
    - sanjay@nitsan.in

# This is executed for all stages
before_install:
  - if php -i | grep -v TRAVIS_CMD | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
  - mkdir -p .Build/external
  - git clone https://github.com/helhum/TYPO3-testing-framework.git .Build/external/nimut-testing-framework -b allow-php73
  - composer config repositories.testing-framework vcs .Build/external/nimut-testing-framework

install:
  - export COMPOSER_ROOT_VERSION=5.6.0
  - |
    composer require \
      typo3/cms-backend="$TYPO3_VERSION" \
      typo3/cms-core="$TYPO3_VERSION" \
      typo3/cms-extbase="$TYPO3_VERSION" \
      typo3/cms-extensionmanager="$TYPO3_VERSION" \
      typo3/cms-fluid="$TYPO3_VERSION" \
      typo3/cms-frontend="$TYPO3_VERSION" \
      typo3/cms-install="$TYPO3_VERSION" \
      typo3/cms-scheduler="$TYPO3_VERSION" \
      typo3/cms-recordlist="$TYPO3_VERSION" \
      $PREFER_LOWEST
  - git checkout composer.json

# Test scripts
script:
  - .Build/bin/parallel-lint --exclude .Build .
  # This fails when command reference is not up to date
  - ./typo3cms commandreference:render > /dev/null 2>&1 && test -z "$(git diff --shortstat 2> /dev/null | tail -n1)";
  - git diff
  - .Build/bin/phpunit;

# Configure build stages (with build matrix above, test stage is implicitly defined)
jobs:
  allow_failures:
    - env: TYPO3_VERSION="dev-master"
  include:
    - stage: test
      php: 7.3
      env: TYPO3_VERSION="~9.5.0" TYPO3_UPGRADE_FROM_VERSION="~9.5.0"
    - stage: test
      php: 7.2
      env: TYPO3_VERSION="~9.5.0"
    
    - stage: sonar code scanner
      if: type = push AND branch IN (master, develop)
      php: 7.2
      before_install: skip
      install: skip
      before_script:
        - mkdir -p .Build/external
        - git clone https://github.com/helhum/TYPO3-testing-framework.git .Build/external/nimut-testing-framework -b allow-php73
        - composer config repositories.testing-framework vcs .Build/external/nimut-testing-framework
      script:
        - git fetch --unshallow
        - export COMPOSER_ROOT_VERSION=5.6.0
        - composer install
        - .Build/bin/phpunit --whitelist Classes --coverage-clover .Build/clover.xml --log-junit .Build/junit.xml
        - >
          if [ -n "$SONAR_TOKEN" ]; then
            sonar-scanner
          fi
